version: '3.9'

services:
  db:
    image: postgres
    restart: always
    shm_size: 512mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres-db-volume:
